services:
  main_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - detector
      - enhancer
    networks:
      - app-network

  detector:
    build:
      context: .
      dockerfile: ./models/detector/Dockerfile
    networks:
      - app-network

  enhancer:
    build:
      context: .
      dockerfile: ./models/enhancer/Dockerfile
    networks:
      - app-network

  demo:
    build:
      context: .
      dockerfile: ./demo/Dockerfile
    ports:
      - "5555:5000"
    networks:
      - app-network
    profiles:
      - demo

networks:
  app-network:
    driver: bridge
