# start from dockerfiles, they are probably not optimal
# not tested, need to add network, make sense of ports, volumes
# version: '3'
services:
  main_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - detector
      - enhancer

  detector:
    build:
      context: .
      dockerfile: ./models/detector/Dockerfile
    ports:
      - "8001:8000"

  enhancer:
    build:
      context: .
      dockerfile: ./models/enhancer/Dockerfile
    ports:
      - "8002:8000"
